### ISSUE TITLE
Rails server keeps quitting after calling functions from the library

### ISSUE THREAD

**Issue by varun43in** [Nakilon/dhash-vips#17]
Hi guys, first of all thanks for this amazing gem!  IDHash works beautifully.

I'm experiencing a very weird issue where my rails server keeps crashing after I call an action that uses the gem
I confirmed this by calling other actions that aren't using the gem and the server stays alive, so I know it's something to do with the gem.

Has anyone experience this?  Help greatly appreciated.

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
Rails 7.0.2.4

Gemfile:
gem "dhash-vips"

Running windows 10

Thanks!

**Comment by Nakilon** [comment]
Hello.
How do you invoke the gem methods? And how does the server crash?
For now the only Rails issue I've heard was hanging. See https://github.com/Nakilon/dhash-vips/issues/10 and links.

**Comment by Nakilon** [comment]
I'm gonna close it since it's been a year.
