### ISSUE TITLE
Use Dhash for comparing a set of 5  images to frames from video to match the image?

### ISSUE THREAD

**Issue by amrithmmh** [Nakilon/dhash-vips#2]
Is it possible to use Dhash to compare for similarity(it will be exactly same anyway because the output is from a handheld atm swipe machine screen) to video frames (even 1fps will do the job)
so i can match the image to template(template matching seems a fit but not really working well for me)
and do a task like send a message?

I will be using openCV (c++ or python doesnt realy matter) and planning to implement on raspberry pi and 5Mp camera attached

**Comment by Nakilon** [comment]
Am I right that you want to classify the video as one of 5 classes? Yeah, you can have 5 fingerprints and then fingerprint each frame to compare with them.

Quick googling tells me that libvips should also work on Raspberry Pi -- there is a 2015 year note about it in blog http://libvips.blogspot.com/2015/03/now-there-are-four-cores-and-better.html, @jcupitt may provide fresh knowledge.

Not sure how you are going to apply openCV if once you have the picture the vips processes it, converts to a resized b/w image and then the dhash-vips fingerprints it. Maybe it can make things faster by finding the "keyframes" to skip processing next frame that has no much difference but this depends on the kind of video you have.

**Comment by amrithmmh** [comment]
@Nakilon thanks
